name: CI/CD Pipeline

env:
  DOCKER_USERNAME="minnie34"
  DOCKER_PASSWORD="dckr_pat_IjlK03kAHZe5u2k6amNnSlSJa9g"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from .env


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{env.DOCKER_PASSWORD}} | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: minnie34/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml